name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Fix audit
      run: npm audit fix
    - name: Run Integration Tests
      run: npm run test:unit
