name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Fix audit
      run: npm audit fix
    - name: Display Username
      run: bash "Gabcho333

  integration_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Fix audit
      run: npm audit fix
    - name: Run Integration Tests
      run: npm run test:unit

  ui_tests:
    needs: integration_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Fix audit
      run: npm audit fix
    - name: Install Playwight Browsers
      run: npx playwright install
    - name: Run application
      run: npm start &
    - name: Run UI Tests
      run: npm run test:ui
